### ISSUE TITLE
Ormolu rejects

### ISSUE THREAD

**Issue by georgefst** [parsonsmatt/fourmolu#19]
A list of features rejected by Tweag (not quite definitively in some cases) that we might want to have as options:

- [ ] Prettier and more diff-friendly import/export lists: tweag/ormolu#409
- [ ] Respect more newlines: tweag/ormolu#74 (parts of this have been implemented in Ormolu)
  - [ ] Import groups
    - It's worth thinking about how this plays along with tooling for auto-inserting imports e.g. HLS
  - [ ] Not always one line between top-level definitions
    - Multiple blank lines can be useful for semantic grouping
    - Zero is nice for trivial definitions, especially instances
- [ ] Break up long lines: tweag/ormolu#508
  - It's possible that this contradicts Ormolu's design enough to be a nightmare to implement fully
- [ ] No space before record opening brace: tweag/ormolu#565

**Comment by ProofOfKeags** [comment]
I just opened #45 as an explicit issue regarding import stanzas. HLS will insert auto imports immediately under the last import statement in your module. If there is a common pattern around stanzas we could encode the preferences in pragmas such that the total set of imports could uniquely determine the import grouping.

**Comment by YellowOnion** [comment]
Stylish Haskell has qualified import's aligned column wise, any chance to have it look like this?

```hs
import           Control.Concurrent       (getNumCapabilities)
import           Control.Concurrent.Async
import           Control.Concurrent.MVar
import           Control.Monad            (forM_, when)
import           GHC.Clock
import qualified System.Posix             as Unix
```

**Comment by brandonchinn178** [comment]
Feel free to open a new issue! Personally, I don't know why anyone would prefer that format, especially with ImportQualifiedPost, but if people are interested, feel free to submit a PR
